const Data = [
  {
    serialNumber: "12345",
    email: "123@gmail.com",
    jenisMesin: ["Mesin 1", "Mesin 2", "Mesin 3"],
    detail: {
      Mesin1: [
        {
          namaSparepart: "capping station L1100",
          tanggal: "21/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "proses",
        },
        {
          namaSparepart: "Baut Epson 1100",
          tanggal: "19/04/2021",
          Teknisi: "BP Malang",
          jumlah: "20",
          status: "Selesai",
        },
        {
          namaSparepart: "Mur Epson 1100",
          tanggal: "11/04/2021",
          Teknisi: "BP Makasar",
          jumlah: "32",
          status: "Selesai",
        },
      ],
      Mesin2: [
        {
          namaSparepart: "capping station L1200",
          tanggal: "19/05/2021",
          Teknisi: "BP jember",
          jumlah: "9",
          status: "proses",
        },
        {
          namaSparepart: "baut Epson L1200",
          tanggal: "09/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "2",
          status: "Selesai",
        },
        {
          namaSparepart: "mur Epson L1200",
          tanggal: "15/04/2021",
          Teknisi: "BP Malang",
          jumlah: "5",
          status: "Selesai",
        },
      ],
      Mesin3: [
        {
          namaSparepart: "capping station L1300",
          tanggal: "02/05/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "proses",
        },
        {
          namaSparepart: "capping station L1300",
          tanggal: "12/06/2021",
          Teknisi: "BP Surabaya",
          jumlah: "16",
          status: "proses",
        },
        {
          namaSparepart: "capping station L1300",
          tanggal: "12/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "proses",
        },
      ],
    },
  },
  {
    serialNumber: "56789",
    email: "456@gmail.com",
    jenisMesin: ["Mesin 4", "Mesin 5", "Mesin 6"],
    detail: {
      Mesin4: [
        {
          namaSparepart: "capping station L400",
          tanggal: "21/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "proses",
        },
        {
          namaSparepart: "Baut Epson 1400",
          tanggal: "19/04/2021",
          Teknisi: "BP Malang",
          jumlah: "20",
          status: "Selesai",
        },
        {
          namaSparepart: "Mur Epson 1400",
          tanggal: "11/04/2021",
          Teknisi: "BP Makasar",
          jumlah: "32",
          status: "Selesai",
        },
      ],
      Mesin5: [
        {
          namaSparepart: "capping station L500",
          tanggal: "19/05/2021",
          Teknisi: "BP jember",
          jumlah: "9",
          status: "proses",
        },
        {
          namaSparepart: "baut Epson L500",
          tanggal: "09/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "2",
          status: "Selesai",
        },
        {
          namaSparepart: "mur Epson L500",
          tanggal: "15/04/2021",
          Teknisi: "BP Malang",
          jumlah: "5",
          status: "Selesai",
        },
      ],
      Mesin6: [
        {
          namaSparepart: "capping station L600",
          tanggal: "02/05/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "proses",
        },
        {
          namaSparepart: "capping station L600",
          tanggal: "12/06/2021",
          Teknisi: "BP Surabaya",
          jumlah: "16",
          status: "proses",
        },
        {
          namaSparepart: "capping station L600",
          tanggal: "12/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "Selesai",
        },
      ],
    },
  },
  {
    serialNumber: "10111213",
    email: "789@gmail.com",
    jenisMesin: ["Mesin 7", "Mesin 8", "Mesin 9"],
    detail: {
      Mesin7: [
        {
          namaSparepart: "capping station L700",
          tanggal: "21/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "12",
          status: "proses",
        },
        {
          namaSparepart: "Baut Epson 1700",
          tanggal: "19/04/2021",
          Teknisi: "BP Malang",
          jumlah: "20",
          status: "Selesai",
        },
        {
          namaSparepart: "Mur Epson 1700",
          tanggal: "11/04/2021",
          Teknisi: "BP Makasar",
          jumlah: "32",
          status: "Selesai",
        },
      ],
      Mesin8: [
        {
          namaSparepart: "capping station L800",
          tanggal: "19/05/2021",
          Teknisi: "BP jember",
          jumlah: "11",
          status: "proses",
        },
        {
          namaSparepart: "baut Epson L800",
          tanggal: "09/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "20",
          status: "Selesai",
        },
        {
          namaSparepart: "mur Epson L800",
          tanggal: "15/04/2021",
          Teknisi: "BP Malang",
          jumlah: "12",
          status: "Selesai",
        },
      ],
      Mesin9: [
        {
          namaSparepart: "capping station L900",
          tanggal: "02/05/2021",
          Teknisi: "BP Surabaya",
          jumlah: "3",
          status: "proses",
        },
        {
          namaSparepart: "capping station L900",
          tanggal: "12/06/2021",
          Teknisi: "BP Surabaya",
          jumlah: "5",
          status: "proses",
        },
        {
          namaSparepart: "capping station L900",
          tanggal: "12/04/2021",
          Teknisi: "BP Surabaya",
          jumlah: "22",
          status: "Selesai",
        },
      ],
    },
  },
];
export default Data;
